<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Grok.Player.Core</RootNamespace>
    <AssemblyName>Grok.Player.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.11" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Grok.Player.Core.Tests" />
    <InternalsVisibleTo Include="Grok.Player.Core.IntegrationTests" />
    <InternalsVisibleTo Include="YoutubeProbe" />
  </ItemGroup>

</Project>
